version: '3.4'

services:
  sqlserver: 
    image: mcr.microsoft.com/mssql/server:2019-latest

  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Systems/Api/Dockerfile
    depends_on:
      - sqlserver

  identity:
    image: ${DOCKER_REGISTRY-}identity
    build:
      context: .
      dockerfile: Systems/Identity/Dockerfile
    depends_on:
      - sqlserver