version: '3.4'

services:
  sqlserver: 
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Passw(0)rd
    ports:
      - "21433:1433"
    networks:
      - check_list_network
  
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - CONNECTION_STRING_HOST=sqlserver
      - CONNECTION_STRING_DATABASE=CheckListNet
      - CONNECTION_STRING_USER=sa
      - CONNECTION_STRING_PASSWORD=Passw(0)rd
      - IDENTITY_SERVER_URL=http://host.docker.internal:20001
      - IDENTITY_SERVER_CLIENT_ID=frontend
      - IDENTITY_SERVER_CLIENT_SECRET=secret
      - GENERAL_SWAGGER_VISIBLE=true
    ports:
      - "20000:80"
    networks:
      - check_list_network

  identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - CONNECTION_STRING_HOST=sqlserver
      - CONNECTION_STRING_DATABASE=CheckListNet
      - CONNECTION_STRING_USER=sa
      - CONNECTION_STRING_PASSWORD=Passw(0)rd

    ports:
      - "20001:80"
    networks:
      - check_list_network

networks:
  check_list_network:
    name: CheckListNet
    driver: bridge